builds:
  - binary: ax
    main: ./cmd/ax
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"
  